# Data exploration

In [1]:
import pandas as pd
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, random_split


CSV_FILE_TRAIN = "data/train.csv"
CSV_FILE_TEST = "data/test.csv"

df = pd.read_csv(CSV_FILE_TRAIN)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## Is Sex a factor in the survival rate ?

In [2]:
#  Sex statistics
missing = df['Sex'].isnull().sum()
print(f"Number of null value is {missing}")

Number of null value is 0

In [3]:
# Sex distribution
df.groupby('Sex')['PassengerId'].count()

Sex
female    314
male      577
Name: PassengerId, dtype: int64

In [4]:
# Survival rate per sex
df.groupby('Sex')['Survived'].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

Conclusion: females have a 74% survival rate, while males have a 18% survival rate.

## Is socio-economic status (through PClass column) a factor ?

In [5]:
#  Pclass statistics
missing = df['Pclass'].isna().sum()
mean = df['Pclass'].mean()
std = df['Pclass'].std()
print(f"Number of null value is {missing}")
print(f"Mean is {mean}")
print(f"Standard deviation is {std}")

Number of null value is 0
Mean is 2.308641975308642
Standard deviation is 0.836071240977049

In [6]:
# Pclass distribution
df.groupby('Pclass')['PassengerId'].count()

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [7]:
# Survival rate per Pclass
df.groupby('Pclass')['Survived'].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

Conclusion: 1st class has a 62% survival rate while 3rd class has a 24% survival rate

Is age a factor in the survival rate ?

In [8]:
#  Age statistics
missing = df['Age'].isna().sum()
mean = df['Age'].mean()
std = df['Age'].std()
print(f"Number of missing value is {missing}")
print(f"Mean is {mean}")
print(f"Standard deviation is {std}")

Number of missing value is 177
Mean is 29.69911764705882
Standard deviation is 14.526497332334042

In [9]:
# Age group distribution
def get_age_group(age):
    if age <= 10:
        return '0-10'
    elif age <= 20:
        return '10-20'
    elif age <= 30:
        return '20-30'
    elif age <= 40:
        return '30-40'
    elif age <= 50:
        return '40-50'
    elif age <= 60:
        return '50-60'
    elif age <= 70:
        return '60-70'
    elif age <= 80:
        return '70-80'
    else:
        return '80+'


# Remove records where age is missing
df_with_age = df[df['Age'].notna()]

# Create new 'age_group' column
df_with_age['age_group'] = df_with_age['Age'].apply(get_age_group)
df_with_age.groupby('age_group')['PassengerId'].count()

/tmp/ipykernel_797/2107776763.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_with_age['age_group'] = df_with_age['Age'].apply(get_age_group)

age_group
0-10      64
10-20    115
20-30    230
30-40    155
40-50     86
50-60     42
60-70     17
70-80      5
Name: PassengerId, dtype: int64

In [10]:
# Survival rate per age group
df_with_age.groupby('age_group')['Survived'].mean()

age_group
0-10     0.593750
10-20    0.382609
20-30    0.365217
30-40    0.445161
40-50    0.383721
50-60    0.404762
60-70    0.235294
70-80    0.200000
Name: Survived, dtype: float64

Conclusions:
    - children (< 10yo) are more likely to survive
    - elderly people > 60yo have are less likely to survive

As a first iteration, a small model could be created with the following features: sex, pclass, age group.

# Data preparation

In [11]:
# Keep columns relevant to our model
dfnorm = df.loc[:, ['PassengerId', 'Survived', 'Sex', 'Pclass']]

In [12]:
# Set Sex=1 for female and Sex=0 for male
dfnorm['Sex'] = dfnorm['Sex'].map({'female': 1, 'male': 0})

In [13]:
dfnorm

     PassengerId  Survived  Sex  Pclass
0              1         0    0       3
1              2         1    1       1
2              3         1    1       3
3              4         1    1       1
4              5         0    0       3
..           ...       ...  ...     ...
886          887         0    0       2
887          888         1    1       1
888          889         0    1       3
889          890         1    0       1
890          891         0    0       3

[891 rows x 4 columns]

## Load data in Pytorch datasets

In [14]:
class TitanicDataset(Dataset):
    def __init__(self, csv_file, features_cols, label_col=None):
        """
        Initialize Dataset from CSV file
        """
        self.data = pd.read_csv(csv_file)
        self.features_cols = features_cols
        self.label_col = label_col
        self.has_labels = label_col is not None

        # Set Sex=1 for female and Sex=0 for male
        self.data['Sex'] = self.data['Sex'].map({'female': 1, 'male': 0})

        # Convert data into pytorch tensors
        self.features = torch.tensor(self.data[features_cols].values, dtype=torch.float32)
        if self.has_labels:
            self.labels = torch.tensor(self.data[self.label_col].values, dtype=torch.long)

    def __len__(self):
        """
        Retourne le nombre d'échantillons.
        """
        return len(self.data)

    def __getitem__(self, index):
        """
        Retourne un échantillon (features, label) à l'index donné.
        """
        if self.has_labels:
            return self.features[index], self.labels[index]
        else:
            return self.features[index]


features_cols = ['Sex', 'Pclass']
label_col = 'Survived'

# Use 80% of the dataset to train our model
# Remaning 20% are used to validate the model with unseen data (validation dataset)
train_dataset_length_pct = 0.8
val_dataset_length_pct = 1 - train_dataset_length_pct

dataset = TitanicDataset(CSV_FILE_TRAIN, features_cols, label_col)
train_dataset, val_dataset = random_split(dataset, lengths=[train_dataset_length_pct, val_dataset_length_pct])

# Model training

## Create neural network

In [15]:
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")


# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(2, 4),
            nn.ReLU(),
            nn.Linear(4, 2)
        )

    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits


model = NeuralNetwork().to(device)
print(model)

Using cpu device
NeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=2, out_features=4, bias=True)
    (1): ReLU()
    (2): Linear(in_features=4, out_features=2, bias=True)
  )
)

In [16]:
batch_size = 16
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

In [17]:
def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    # Set the model to training mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 8 == 0:
            loss, current = loss.item(), batch * batch_size + len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    # Set the model to evaluation mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.eval()
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    # Evaluating the model with torch.no_grad() ensures that no gradients are computed during test mode
    # also serves to reduce unnecessary gradient computations and memory usage for tensors with requires_grad=True
    with torch.no_grad():
        for X, y in dataloader:
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

In [18]:
learning_rate = 1e-2
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

epochs = 50
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(val_dataloader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 1.052557  [   16/  713]
loss: 0.832374  [  144/  713]
loss: 0.944394  [  272/  713]
loss: 0.742737  [  400/  713]
loss: 0.726448  [  528/  713]
loss: 0.727456  [  656/  713]
Test Error:
 Accuracy: 42.7%, Avg loss: 0.705291

Epoch 2
-------------------------------
loss: 0.729238  [   16/  713]
loss: 0.699369  [  144/  713]
loss: 0.683726  [  272/  713]
loss: 0.655938  [  400/  713]
loss: 0.676654  [  528/  713]
loss: 0.651572  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.659462

Epoch 3
-------------------------------
loss: 0.654351  [   16/  713]
loss: 0.664695  [  144/  713]
loss: 0.592687  [  272/  713]
loss: 0.625535  [  400/  713]
loss: 0.665012  [  528/  713]
loss: 0.617610  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.642275

Epoch 4
-------------------------------
loss: 0.620111  [   16/  713]
loss: 0.645828  [  144/  713]
loss: 0.542969  [  272/  713]
loss: 0.610886  [  400/  713]
loss: 0.662270  [  528/  713]
loss: 0.596395  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.633318

Epoch 5
-------------------------------
loss: 0.601442  [   16/  713]
loss: 0.632132  [  144/  713]
loss: 0.510931  [  272/  713]
loss: 0.602057  [  400/  713]
loss: 0.661746  [  528/  713]
loss: 0.580754  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.627054

Epoch 6
-------------------------------
loss: 0.590647  [   16/  713]
loss: 0.620619  [  144/  713]
loss: 0.488809  [  272/  713]
loss: 0.596580  [  400/  713]
loss: 0.661041  [  528/  713]
loss: 0.567773  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.621164

Epoch 7
-------------------------------
loss: 0.584185  [   16/  713]
loss: 0.610075  [  144/  713]
loss: 0.472328  [  272/  713]
loss: 0.592859  [  400/  713]
loss: 0.659440  [  528/  713]
loss: 0.556029  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.614854

Epoch 8
-------------------------------
loss: 0.580221  [   16/  713]
loss: 0.599986  [  144/  713]
loss: 0.458995  [  272/  713]
loss: 0.590031  [  400/  713]
loss: 0.657021  [  528/  713]
loss: 0.544868  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.608032

Epoch 9
-------------------------------
loss: 0.577817  [   16/  713]
loss: 0.590152  [  144/  713]
loss: 0.447382  [  272/  713]
loss: 0.587636  [  400/  713]
loss: 0.654211  [  528/  713]
loss: 0.534081  [  656/  713]
Test Error:
 Accuracy: 59.0%, Avg loss: 0.600954

Epoch 10
-------------------------------
loss: 0.576322  [   16/  713]
loss: 0.580489  [  144/  713]
loss: 0.436811  [  272/  713]
loss: 0.585657  [  400/  713]
loss: 0.651397  [  528/  713]
loss: 0.523351  [  656/  713]
Test Error:
 Accuracy: 71.9%, Avg loss: 0.593678

Epoch 11
-------------------------------
loss: 0.575843  [   16/  713]
loss: 0.571033  [  144/  713]
loss: 0.426410  [  272/  713]
loss: 0.583209  [  400/  713]
loss: 0.648496  [  528/  713]
loss: 0.512670  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.586319

Epoch 12
-------------------------------
loss: 0.576103  [   16/  713]
loss: 0.561725  [  144/  713]
loss: 0.416345  [  272/  713]
loss: 0.580748  [  400/  713]
loss: 0.645748  [  528/  713]
loss: 0.502164  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.579007

Epoch 13
-------------------------------
loss: 0.577016  [   16/  713]
loss: 0.552576  [  144/  713]
loss: 0.406493  [  272/  713]
loss: 0.578231  [  400/  713]
loss: 0.643265  [  528/  713]
loss: 0.491874  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.571937

Epoch 14
-------------------------------
loss: 0.578434  [   16/  713]
loss: 0.543661  [  144/  713]
loss: 0.397307  [  272/  713]
loss: 0.576089  [  400/  713]
loss: 0.640636  [  528/  713]
loss: 0.483165  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.565005

Epoch 15
-------------------------------
loss: 0.580442  [   16/  713]
loss: 0.535099  [  144/  713]
loss: 0.388446  [  272/  713]
loss: 0.574244  [  400/  713]
loss: 0.638354  [  528/  713]
loss: 0.475125  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.558560

Epoch 16
-------------------------------
loss: 0.582762  [   16/  713]
loss: 0.526816  [  144/  713]
loss: 0.379614  [  272/  713]
loss: 0.572286  [  400/  713]
loss: 0.636651  [  528/  713]
loss: 0.467419  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.552672

Epoch 17
-------------------------------
loss: 0.585292  [   16/  713]
loss: 0.518799  [  144/  713]
loss: 0.370865  [  272/  713]
loss: 0.570244  [  400/  713]
loss: 0.635371  [  528/  713]
loss: 0.460141  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.547186

Epoch 18
-------------------------------
loss: 0.588152  [   16/  713]
loss: 0.511088  [  144/  713]
loss: 0.362338  [  272/  713]
loss: 0.568164  [  400/  713]
loss: 0.634440  [  528/  713]
loss: 0.453297  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.542119

Epoch 19
-------------------------------
loss: 0.591291  [   16/  713]
loss: 0.503700  [  144/  713]
loss: 0.354108  [  272/  713]
loss: 0.566071  [  400/  713]
loss: 0.633806  [  528/  713]
loss: 0.446906  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.537442

Epoch 20
-------------------------------
loss: 0.594696  [   16/  713]
loss: 0.496656  [  144/  713]
loss: 0.346236  [  272/  713]
loss: 0.563990  [  400/  713]
loss: 0.633427  [  528/  713]
loss: 0.440969  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.533142

Epoch 21
-------------------------------
loss: 0.598331  [   16/  713]
loss: 0.489973  [  144/  713]
loss: 0.338755  [  272/  713]
loss: 0.561937  [  400/  713]
loss: 0.633268  [  528/  713]
loss: 0.435478  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.529208

Epoch 22
-------------------------------
loss: 0.602153  [   16/  713]
loss: 0.483662  [  144/  713]
loss: 0.331682  [  272/  713]
loss: 0.559927  [  400/  713]
loss: 0.633299  [  528/  713]
loss: 0.430421  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.525625

Epoch 23
-------------------------------
loss: 0.606118  [   16/  713]
loss: 0.477730  [  144/  713]
loss: 0.325024  [  272/  713]
loss: 0.557971  [  400/  713]
loss: 0.633488  [  528/  713]
loss: 0.425778  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.522374

Epoch 24
-------------------------------
loss: 0.610180  [   16/  713]
loss: 0.472176  [  144/  713]
loss: 0.318785  [  272/  713]
loss: 0.556076  [  400/  713]
loss: 0.633806  [  528/  713]
loss: 0.421527  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.519434

Epoch 25
-------------------------------
loss: 0.614298  [   16/  713]
loss: 0.466996  [  144/  713]
loss: 0.312959  [  272/  713]
loss: 0.554251  [  400/  713]
loss: 0.634224  [  528/  713]
loss: 0.417645  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.516782

Epoch 26
-------------------------------
loss: 0.618434  [   16/  713]
loss: 0.462181  [  144/  713]
loss: 0.307537  [  272/  713]
loss: 0.552499  [  400/  713]
loss: 0.634715  [  528/  713]
loss: 0.414106  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.514395

Epoch 27
-------------------------------
loss: 0.622552  [   16/  713]
loss: 0.457719  [  144/  713]
loss: 0.302504  [  272/  713]
loss: 0.550823  [  400/  713]
loss: 0.635256  [  528/  713]
loss: 0.410883  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.512249

Epoch 28
-------------------------------
loss: 0.626620  [   16/  713]
loss: 0.453595  [  144/  713]
loss: 0.297846  [  272/  713]
loss: 0.549225  [  400/  713]
loss: 0.635824  [  528/  713]
loss: 0.407950  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.510321

Epoch 29
-------------------------------
loss: 0.630614  [   16/  713]
loss: 0.449791  [  144/  713]
loss: 0.293542  [  272/  713]
loss: 0.547705  [  400/  713]
loss: 0.636401  [  528/  713]
loss: 0.405282  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.508587

Epoch 30
-------------------------------
loss: 0.634510  [   16/  713]
loss: 0.446289  [  144/  713]
loss: 0.289574  [  272/  713]
loss: 0.546261  [  400/  713]
loss: 0.636972  [  528/  713]
loss: 0.402855  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.507027

Epoch 31
-------------------------------
loss: 0.638291  [   16/  713]
loss: 0.443070  [  144/  713]
loss: 0.285921  [  272/  713]
loss: 0.544892  [  400/  713]
loss: 0.637523  [  528/  713]
loss: 0.400646  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.505622

Epoch 32
-------------------------------
loss: 0.641942  [   16/  713]
loss: 0.440113  [  144/  713]
loss: 0.282561  [  272/  713]
loss: 0.543595  [  400/  713]
loss: 0.638044  [  528/  713]
loss: 0.398634  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.504353

Epoch 33
-------------------------------
loss: 0.645454  [   16/  713]
loss: 0.437401  [  144/  713]
loss: 0.279474  [  272/  713]
loss: 0.542366  [  400/  713]
loss: 0.638527  [  528/  713]
loss: 0.396799  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.503204

Epoch 34
-------------------------------
loss: 0.648819  [   16/  713]
loss: 0.434914  [  144/  713]
loss: 0.276641  [  272/  713]
loss: 0.541204  [  400/  713]
loss: 0.638967  [  528/  713]
loss: 0.395123  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.502161

Epoch 35
-------------------------------
loss: 0.652034  [   16/  713]
loss: 0.432634  [  144/  713]
loss: 0.274042  [  272/  713]
loss: 0.540103  [  400/  713]
loss: 0.639358  [  528/  713]
loss: 0.393590  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.501211

Epoch 36
-------------------------------
loss: 0.655096  [   16/  713]
loss: 0.430544  [  144/  713]
loss: 0.271658  [  272/  713]
loss: 0.539062  [  400/  713]
loss: 0.639700  [  528/  713]
loss: 0.392185  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.500343

Epoch 37
-------------------------------
loss: 0.658005  [   16/  713]
loss: 0.428628  [  144/  713]
loss: 0.269473  [  272/  713]
loss: 0.538076  [  400/  713]
loss: 0.639989  [  528/  713]
loss: 0.390896  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.499545

Epoch 38
-------------------------------
loss: 0.660764  [   16/  713]
loss: 0.426870  [  144/  713]
loss: 0.267469  [  272/  713]
loss: 0.537141  [  400/  713]
loss: 0.640228  [  528/  713]
loss: 0.389710  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.498811

Epoch 39
-------------------------------
loss: 0.663376  [   16/  713]
loss: 0.425258  [  144/  713]
loss: 0.265633  [  272/  713]
loss: 0.536256  [  400/  713]
loss: 0.640416  [  528/  713]
loss: 0.388617  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.498132

Epoch 40
-------------------------------
loss: 0.665845  [   16/  713]
loss: 0.423777  [  144/  713]
loss: 0.263950  [  272/  713]
loss: 0.535416  [  400/  713]
loss: 0.640554  [  528/  713]
loss: 0.387608  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.497501

Epoch 41
-------------------------------
loss: 0.668176  [   16/  713]
loss: 0.422417  [  144/  713]
loss: 0.262407  [  272/  713]
loss: 0.534618  [  400/  713]
loss: 0.640646  [  528/  713]
loss: 0.386674  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.496913

Epoch 42
-------------------------------
loss: 0.670375  [   16/  713]
loss: 0.421167  [  144/  713]
loss: 0.260992  [  272/  713]
loss: 0.533860  [  400/  713]
loss: 0.640693  [  528/  713]
loss: 0.385807  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.496363

Epoch 43
-------------------------------
loss: 0.672449  [   16/  713]
loss: 0.420015  [  144/  713]
loss: 0.259694  [  272/  713]
loss: 0.533140  [  400/  713]
loss: 0.640698  [  528/  713]
loss: 0.385002  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.495847

Epoch 44
-------------------------------
loss: 0.674403  [   16/  713]
loss: 0.418954  [  144/  713]
loss: 0.258503  [  272/  713]
loss: 0.532454  [  400/  713]
loss: 0.640664  [  528/  713]
loss: 0.384252  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.495361

Epoch 45
-------------------------------
loss: 0.676245  [   16/  713]
loss: 0.417976  [  144/  713]
loss: 0.257409  [  272/  713]
loss: 0.531801  [  400/  713]
loss: 0.640593  [  528/  713]
loss: 0.383553  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.494902

Epoch 46
-------------------------------
loss: 0.677980  [   16/  713]
loss: 0.417072  [  144/  713]
loss: 0.256405  [  272/  713]
loss: 0.531178  [  400/  713]
loss: 0.640490  [  528/  713]
loss: 0.382898  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.494468

Epoch 47
-------------------------------
loss: 0.679615  [   16/  713]
loss: 0.416237  [  144/  713]
loss: 0.255482  [  272/  713]
loss: 0.530583  [  400/  713]
loss: 0.640356  [  528/  713]
loss: 0.382285  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.494055

Epoch 48
-------------------------------
loss: 0.681156  [   16/  713]
loss: 0.415463  [  144/  713]
loss: 0.254633  [  272/  713]
loss: 0.530015  [  400/  713]
loss: 0.640194  [  528/  713]
loss: 0.381710  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.493661

Epoch 49
-------------------------------
loss: 0.682609  [   16/  713]
loss: 0.414746  [  144/  713]
loss: 0.253852  [  272/  713]
loss: 0.529472  [  400/  713]
loss: 0.640008  [  528/  713]
loss: 0.381169  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.493286

Epoch 50
-------------------------------
loss: 0.683981  [   16/  713]
loss: 0.414080  [  144/  713]
loss: 0.253133  [  272/  713]
loss: 0.528952  [  400/  713]
loss: 0.639800  [  528/  713]
loss: 0.380659  [  656/  713]
Test Error:
 Accuracy: 80.3%, Avg loss: 0.492928

Done!

# Prepare predictions

In [36]:
def predict(dataloader, model):
    # Set the model to evaluation mode - important for batch normalization and dropout layers
    # Unnecessary in this situation but added for best practices
    model.eval()
    # Initiliaze empty tensor that will contain our predictions
    pred = torch.tensor([])
    with torch.no_grad():
        for X in dataloader:
            logits = model(X)
            batch_pred = logits.argmax(1)
            pred = torch.cat((pred, batch_pred))
    return pred

In [39]:
features_cols = ['Sex', 'Pclass']
test_batch_size=64

test_dataset = TitanicDataset(CSV_FILE_TEST, features_cols)
test_dataloader = DataLoader(test_dataset, batch_size=test_batch_size, shuffle=False)
pred = predict(test_dataloader, model)
pred

tensor([0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
        1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1.,
        0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0.,
        1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
        0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.,
        0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0.,
        1., 0., 0., 0.])